spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app?createDatabaseIfNotExist=true
    username: root
    password: "Akash@2002"

#  hikari:
#    pool-name: neon-hikari
#    maximum-pool-size: 10
#    minimum-idle: 2
#    idle-timeout: 30000        # 30s
#    connection-timeout: 20000  # 20s
#    max-lifetime: 1800000      # 30m (keep below Neon’s TCP idle timeouts)
#    validation-timeout: 5000
#    leak-detection-threshold: 0
#    initialization-fail-timeout: -1  # don't fail app if DB is momentarily unavailable

  jpa:
    hibernate:
      ddl-auto: update     # Auto schema update during development
    show-sql: true         # Show SQL in console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


logging:
  level:
    org.springframework.security: DEBUG


security:
  jwt:
    secret: ${JWT_SECRET:akashjena;salaforcejavadevloeprvkasfbehwqpofhjashofjaswfpojasfvbafop[chiffon[shjfwefjjfslajfsahfoshffasnbash[f}ddvsdbcdcvv745devdedvdvv
    issuer: ${JWT_ISSUER:api.akash.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}
